services:
  server:
    image: spring-gitlab-monitor
    restart: always
    env_file:
      - .env
    ports:
      - 8080:8080
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_passw0rd
      POSTGRES_DB: pg_database
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
