services:
  db:
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env.production
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8888:80"
    env_file:
      - .env.production
